title: SJ's blog
email: 724385768@qq.com
description: >
  PHP/Ruby/Python/Rust  
baseurl: ""
url: ""
github_username:  songjian

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Tag配置
tag_page_layout: tag_page
tag_page_dir: tag

# Tag Feed
# tag_feed_layout: tag_feed
# tag_feed_dir: tag

# 分页设置
paginate: 15
paginate_path: /page:num/


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

minima:
  date_format: "%Y年%m月%d日"
