version: '3'
services:
  app:
    image: jekyll/jekyll:4.2.2
      #    restart: always
    volumes:
      - ./:/srv/jekyll
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "4000:4000"
    command: "jekyll s -wD"
