name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the songjian1984/jekyll container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        songjian1984/jekyll:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: rsync deployments
      uses: contention/rsync-deployments@v1.0.0
      env: 
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        args: "-avzr --delete --exclude .htaccess --exclude /uploads/ sj@113.120.108.155:~/abc/"

