name: test file access

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: curl file
      run: echo $(curl https://github.com/songjian/my-ip-address/raw/master/my-hosts/s2)
